[build]
  command = "SKIP_ENV_VALIDATION=1 npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://pension-backend.vercel.app/api/v1"
  NEXT_PUBLIC_PAYSTACK_BASE_URL = "https://api.paystack.co"

[[plugins]]
  package = "@netlify/plugin-nextjs"
